/*
 * Copyright 2019 NXP
 * All rights reserved.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Pins v7.0
processor: MKE18F512xxx16
package_id: MKE18F512VLL16
mcu_data: ksdk2_0
processor_version: 0.7.2
board: HVP-KE18F
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

#include "fsl_common.h"
#include "fsl_port.h"
#include "fsl_gpio.h"
#include "pin_mux.h"

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitBootPins
 * Description   : Calls initialization functions.
 *
 * END ****************************************************************************************************************/
void BOARD_InitBootPins(void)
{
    BOARD_InitPins();
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitPins:
- options: {callFromInitBoot: 'true', coreID: core0, enableClock: 'true'}
- pin_list:
  - {pin_num: '23', peripheral: GPIOE, signal: 'GPIO, 9', pin_signal: ACMP2_IN2/DAC0_OUT/PTE9/FTM0_CH7/LPUART2_CTS, direction: OUTPUT}
  - {pin_num: '92', peripheral: CoreDebug, signal: TRACE_SWO, pin_signal: PTA10/FTM1_CH4/LPUART0_TX/FXIO_D0/JTAG_TDO/noetm_Trace_SWO, pull_select: down, pull_enable: disable}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitPins(void)
{
    /* Clock Control: Clock enabled */
    CLOCK_EnableClock(kCLOCK_PortA);
    /* Clock Control: Clock enabled */
    CLOCK_EnableClock(kCLOCK_PortE);

    gpio_pin_config_t Salida_config = {
            .pinDirection = kGPIO_DigitalOutput,
            .outputLogic = 0U
        };

   /* gpio_pin_config_t Entrada_config = {
             .pinDirection = kGPIO_DigitalInput,
    		 .outputLogic = 0U
        };*/


    GPIO_PinInit(GPIO_DATA_GPIOD, BOARD_INITPINS_LCD_DB0, &Salida_config);
    GPIO_PinInit(GPIO_DATA_GPIOD, BOARD_INITPINS_LCD_DB1, &Salida_config);
    GPIO_PinInit(GPIO_DATA_GPIOD, BOARD_INITPINS_LCD_DB2, &Salida_config);
    GPIO_PinInit(GPIO_DATA_GPIOD, BOARD_INITPINS_LCD_DB3, &Salida_config);
    GPIO_PinInit(GPIO_DATA_GPIOD, BOARD_INITPINS_LCD_DB4, &Salida_config);
    GPIO_PinInit(GPIO_DATA_GPIOD, BOARD_INITPINS_LCD_DB5, &Salida_config);
    GPIO_PinInit(GPIO_DATA_GPIOD, BOARD_INITPINS_LCD_DB6, &Salida_config);
    GPIO_PinInit(GPIO_DATA_GPIOD, BOARD_INITPINS_LCD_DB7, &Salida_config);

    GPIO_PinInit(GPIO_DATA_GPIOD, BOARD_INITPINS_LCD_RW, &Salida_config);

    GPIO_PinInit(GPIO_DATA_GPIOD, EN_PIN, &Salida_config);

    GPIO_PinInit(BOARD_INITPINS_GPIOE,BOARD_INITPINS_CS2, &Salida_config);
    GPIO_PinInit(BOARD_INITPINS_GPIOE,BOARD_INITPINS_CS1, &Salida_config);

    GPIO_PinInit(BOARD_INITPINS_GPIOE,BOARD_INITPINS_RST, &Salida_config);

    GPIO_PinInit(BOARD_INITPINS_GPIOC, RS_PIN, &Salida_config);


    /* PORTE*/
    PORT_SetPinMux(BOARD_INITPINS_PORTE, BOARD_INITPINS_RST, kPORT_MuxAsGpio);
    PORT_SetPinMux(BOARD_INITPINS_PORTE, BOARD_INITPINS_CS1, kPORT_MuxAsGpio);
    PORT_SetPinMux(BOARD_INITPINS_PORTE, BOARD_INITPINS_CS2, kPORT_MuxAsGpio);

    /* PORTD*/
    PORT_SetPinMux(GPIO_DATA_PORT, BOARD_INITPINS_LCD_DB0, kPORT_MuxAsGpio);
    PORT_SetPinMux(GPIO_DATA_PORT, BOARD_INITPINS_LCD_DB1, kPORT_MuxAsGpio);
    PORT_SetPinMux(GPIO_DATA_PORT, BOARD_INITPINS_LCD_DB2, kPORT_MuxAsGpio);
    PORT_SetPinMux(GPIO_DATA_PORT, BOARD_INITPINS_LCD_DB3, kPORT_MuxAsGpio);
    PORT_SetPinMux(GPIO_DATA_PORT, BOARD_INITPINS_LCD_DB4, kPORT_MuxAsGpio);
    PORT_SetPinMux(GPIO_DATA_PORT, BOARD_INITPINS_LCD_DB5, kPORT_MuxAsGpio);
    PORT_SetPinMux(GPIO_DATA_PORT, BOARD_INITPINS_LCD_DB6, kPORT_MuxAsGpio);
    PORT_SetPinMux(GPIO_DATA_PORT, BOARD_INITPINS_LCD_DB7, kPORT_MuxAsGpio);
    PORT_SetPinMux(GPIO_DATA_PORT, BOARD_INITPINS_LCD_RW, kPORT_MuxAsGpio);
    PORT_SetPinMux(GPIO_DATA_PORT, EN_PIN, kPORT_MuxAsGpio);

    /* PORTC*/

    PORT_SetPinMux(BOARD_INITPINS_PORTC, RS_PIN, kPORT_MuxAsGpio);

}
/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
