/*
 * Copyright 2019 NXP
 * All rights reserved.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

/*! @name PORTE9 (number 23), USER_LED_2
  @{ */
#define BOARD_INITPINS_GPIOE GPIOE /*!<@brief GPIO device name: GPIOE */
#define BOARD_INITPINS_PORTE PORTE /*!<@brief PORT device name: PORTE */

#define BOARD_INITPINS_RST 12U     /*!<@brief PORTE pin index: 12 */
#define BOARD_INITPINS_CS1 3U
#define BOARD_INITPINS_CS2 14U

#define GPIO_DATA_GPIOD GPIOD
#define GPIO_DATA_PORT PORTD


#define BOARD_INITPINS_LCD_DB0 10U
#define BOARD_INITPINS_LCD_DB1 11U
#define BOARD_INITPINS_LCD_DB2 12U
#define BOARD_INITPINS_LCD_DB3 13U
#define BOARD_INITPINS_LCD_DB4 14U
#define BOARD_INITPINS_LCD_DB5 15U
#define BOARD_INITPINS_LCD_DB6 16U
#define BOARD_INITPINS_LCD_DB7 17U

#define BOARD_INITPINS_LCD_RW 6U
#define EN_PIN 7U

#define BOARD_INITPINS_GPIOC GPIOC
#define BOARD_INITPINS_PORTC PORTC

#define RS_PIN 15U                                          /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void);

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
